pipeline:
  build:
    image: golang:1.7
    commands:
      - cp -r /drone/src /go/
      - cd /go/src/github.com/LOG-ED/docker-micro
      - go build 
      - ./docker-micro &
      - sleep 20
      - go test
      
  publish:
    image: plugins/docker
    repo: fminzoni/docker-micro
    username: fminzoni
    password: ${DOCKER_PASSWORD}

services:
  bootstrap:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
  api:
    image: microhq/micro:latest
    command: api
       
    

