workspace:
  base: /go
  path: src/github.com/LOG-ED/docker-micro

pipeline:
  build:
    image: golang:1.7
    commands:
      - go build 
      - ./docker-micro &
      - sleep 15
      - go test

  publish:
    image: plugins/docker
    repo: fminzoni/docker-micro
    username: fminzoni
    password: ${DOCKER_PASSWORD}

services:
  bootstrap:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
  api:
    image: microhq/micro:latest
    command: api