pipeline:
  bootstrap:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    detach: true

  build:
    image: golang:1.7
    commands:
      - cp -r /drone/src /go/
      - cd /go/src/github.com/LOG-ED/docker-micro
      - go build 
      - ./docker-micro
      - sleep 20
      - go run test/client.go
    detach: true

  api:
    image: microhq/micro:latest
    command: web
    detach: true

  test:
    image: golang:1.7
    commands:
      - sleep 15
      - curl http://127.0.0.1:8082/registry?service=docker-micro.srv.task
       
    

