pipeline:
  bootstrap:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    detach: true

  build:
    image: golang:1.7
    commands:
      - cp -r /drone/src /go/
      - cd /go/src/github.com/LOG-ED/docker-micro
      - go build 
      - ./docker-micro
    detach: true

  api:
    image: microhq/micro:latest
    command: web namespace=docker-micro.srv
    detach: true

  test:
    image: golang:1.7
    commands:
      - curl http://127.0.0.1:8080
      - sleep 240  
    

