pipeline:
  bootstrap:
    image: progrium/consul:latest
    commands: -server -bootstrap -rejoin
    detach: true

  build:
    image: golang:1.7
    commands:
      - go get 
      - go build 
      - ./docker-micro &
      - go run test/client.go