pipeline:
  build:
    image: golang:1.7-alpine
    commands:
      - go build 
      - ./docker-micro &
      - go run test/client.go

services:
  consul:
    image: progrium/consul:latest
    commands: -server -bootstrap -rejoin