pipeline:
  bootstrap:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    detach: true

  build:
    image: golang:1.7
    commands:
      - go get 
      - go install 
      - ./go/docker-micro &
      - go run test/client.go