pipeline:
  bootstrap:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    detach: true

  build:
    image: golang:1.7
    commands:
      - cp -r /drone/src /go/
      - cd /go/src/github.com/LOG-ED/docker-micro
      - go get 
      - go build 
      - ./docker-micro &
      - go run test/client.go