FROM golang:1.7-alpine

RUN mkdir -p /go/src/github.com/LOG-ED/docker-micro

COPY . /go/src/github.com/LOG-ED/docker-micro

WORKDIR /go/src/github.com/LOG-ED/docker-micro/client

RUN go install 

ENTRYPOINT ["/go/bin/client"]
